#!/usr/bin/env python3
"""Writes reference/upstream-api.txt: every Ext function bg3se registers, one
per line as "<context> <Module[.Sub]> <Function>", context Both, Client or
Server.

Read from upstream's own DECLARE_MODULE / DECLARE_SUBMODULE blocks (by Norbyte
and the bg3se contributors), so the list covers both contexts and every
level, where the old surface capture came from the server and stopped at the
module.

Usage: tools/upstream-api.py [path to a bg3se checkout]   (default ../bg3se)
"""

import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
checkout = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "..", "..", "bg3se")
root = os.path.join(checkout, "BG3Extender")
if not os.path.isdir(os.path.join(root, "Lua")):
    sys.exit("upstream-api: no bg3se checkout at %s" % checkout)

decl = re.compile(r"DECLARE_(SUB)?MODULE\(\s*(\w+)\s*,\s*(\w+)\s*(?:,\s*(\w+)\s*)?\)")
func = re.compile(r"MODULE_(?:NAMED_)?FUNCTION\(\s*\"?(\w+)\"?")

rows = set()
for dirpath, _, files in os.walk(os.path.join(root, "Lua")):
    for name in files:
        if not name.endswith((".inl", ".cpp", ".h")) or name == "LibraryRegistrationHelpers.h":
            continue
        text = open(os.path.join(dirpath, name), encoding="utf-8", errors="replace").read()
        for m in decl.finditer(text):
            sub = m.group(1) is not None
            module = m.group(2) + ("." + m.group(3) if sub else "")
            context = m.group(4) if sub else m.group(3)
            end = text.find("END_MODULE", m.end())
            for f in func.finditer(text, m.end(), end):
                rows.add((context, module, f.group(1)))

out = os.path.join(HERE, "..", "reference", "upstream-api.txt")
with open(out, "w") as f:
    f.write("# Generated by tools/upstream-api.py from bg3se's module declarations.\n")
    for context, module, name in sorted(rows, key=lambda r: (r[1], r[2], r[0])):
        f.write("%s %s %s\n" % (context, module, name))
print("upstream-api: %d functions to %s" % (len(rows), os.path.relpath(out)))
