// Engine code and data bg3le reaches, found in whatever build is running (see resolve.h).
// Generated by tools/make-sigs.py from v4.73.98.727 and v4.76.31.656; each pattern was unique in both.
// Every function returns a link-time offset, or 0 when the target cannot be found: leave the feature off.
#pragma once

#include <cstdint>

namespace bg3le::target {

// EntityStorageContainer::GetEntityStorage(EntityHandle); identical copies exist, so through a call site
std::uintptr_t EntityStorageLookup();
// ls::FixedString's create-from-string
std::uintptr_t FixedStringCreate();
// ecs::EntityWorld::FlushECBs
std::uintptr_t FlushECBs();
// the grid path search
std::uintptr_t PathSearch();
// the surface transform initialiser
std::uintptr_t TransformInit();
// ls::FileReader's destructor
std::uintptr_t FileReaderDtor();
// ls::FileReader's constructor
std::uintptr_t FileReaderCtor();
// the Wwise manager's SetSwitch
std::uintptr_t WwiseSetSwitch();
// stats functor parser
std::uintptr_t ParseFunctor();
// the path step
std::uintptr_t PathStep();
// SurfaceManager::AddAction
std::uintptr_t AddAction();
// ecl::GameStateMachine::Update
std::uintptr_t MachineUpdate();
// the instruction loading the string-keys manager
std::uintptr_t StringKeysManagerLoad();
// stats functor set construction
std::uintptr_t MakeSet();
// stats functor group split
std::uintptr_t SplitGroups();
// ls::ModuleSettings::IsModded
std::uintptr_t IsModded();
// the surface action factory's create
std::uintptr_t CreateAction();
// the Wwise manager's SetState
std::uintptr_t WwiseSetState();
// the instruction loading the GlobalSwitches
std::uintptr_t GlobalSwitchesLoad();
// ecl::GameStateMachine::SetTargetState
std::uintptr_t SetTargetState();
// OsirisVariableHelper::SavegameVisit
std::uintptr_t VariableHelperVisit();
// the LoadModule state's Exit (a bare ret between padding)
std::uintptr_t LoadModuleExit();
// esv::GameServer::UpdateMessagesToSend
std::uintptr_t UpdateMessagesFunc();
std::uintptr_t StateNames();
std::uintptr_t LoadModuleExitSlot();
std::uintptr_t CursorControlVtable();
std::uintptr_t WwiseVtable();
std::uintptr_t StateMachineVtable();
std::uintptr_t FunctorsVtable();
std::uintptr_t UpdateMessagesSlot();
std::uintptr_t EoCClient();
std::uintptr_t StatsGlobal();
std::uintptr_t BoostsManager();
std::uintptr_t ClientLevelManager();
std::uintptr_t TemplatesCache();
std::uintptr_t LevelManager();
std::uintptr_t SurfaceActionFactory();
std::uintptr_t ParserContext();
std::uintptr_t TextureAtlasMap();
std::uintptr_t TemplatesManager();
std::uintptr_t ResourcesGlobal();
std::uintptr_t PathRoots();
std::uintptr_t InputManager();
std::uintptr_t GlobalSwitches();
std::uintptr_t StringKeysManager();
std::uintptr_t TranslatedStringRepository();
// stats functor executors, by FunctorContextType 1..9
std::uintptr_t FunctorExec1();
std::uintptr_t FunctorExec2();
std::uintptr_t FunctorExec3();
std::uintptr_t FunctorExec4();
std::uintptr_t FunctorExec5();
std::uintptr_t FunctorExec6();
std::uintptr_t FunctorExec7();
std::uintptr_t FunctorExec8();
std::uintptr_t FunctorExec9();
// eoc::SpellPrototype::Init
std::uintptr_t SpellPrototypeInit();
// eoc::StatusPrototype::Init
std::uintptr_t StatusPrototypeInit();
// eoc::InterruptPrototype::Init
std::uintptr_t InterruptPrototypeInit();
// the passive loader
std::uintptr_t PassiveLoader();
// the static boost parser
std::uintptr_t BoostParse();
// its callback
std::uintptr_t BoostInvoke();
// its copy
std::uintptr_t BoostCopy();
// its manager
std::uintptr_t BoostManage();
// the inlined ThreadRegistry index read (mov r14d, fs:disp32), anchored on its function
std::uintptr_t ThreadIndexRead();

}  // namespace bg3le::target
